name: CI

on: [push, pull_request]

jobs:
  smoke-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps (core only)
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy pyarrow==14.0.2 pyyaml

      - name: Import cost_model
        run: |
          python - << 'PY'
import sys, pathlib
sys.path.append('.')
import cost_model
print("✅ cost_model import ok")
PY
